### ISSUE TITLE
Como entro al Modulo?

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#18]
Buen dia!

pos como o donde entro chicos?

saludos

**Comment by caom92** [comment]
Le había mencionado por Skype que tuve problemas con la configuración del redireccionamiento de su servidor y que por eso debían acceder desde http://test.jfdc.tech. La próxima vez que suba cambios, veré si puedo hacer que puedan entrar desde audits.jfdc.tech, pero por lo pronto tendran que usar el enlace anterior

**Comment by delcabo** [comment]
me ayudas con la clave de Administrador  e es password?

**Comment by delcabo** [comment]
gracias
