### ISSUE TITLE
Atributos de Auditor

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#19]
en el caso de dar de Alta a Maricela como auditor, deberia depender de todas las zonas!

entiendo si el Auditado SI corresponde a una zona en particular

**Comment by caom92** [comment]
Los auditores puede hacer auditorías en todas las zonas, sin importar a cuál estén registrados, indicar a qué zona pertenecen al momento de crearles una cuenta de usuario es meramente informativo.
