### ISSUE TITLE
detalles en Add audit (pantalla principal)

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#21]
Auditor solo deja ADD a la zona que se puso por ADMIN 
![image](https://user-images.githubusercontent.com/28766240/38517114-c592cc36-3bed-11e8-9c3a-8b65780cec73.png)

tampoco (SAVE) graba o registra la audtoria, dice "erro de algo"
![image](https://user-images.githubusercontent.com/28766240/38517052-98334f7c-3bed-11e8-9351-b3340d47479b.png)

**Comment by caom92** [comment]
Al reportar un problema por favor siga las instrucciones que le aparecen al principio, para agilizar el poder reproducir el problema.

![screenshot-2018-4-9 caom92 audit-master](https://user-images.githubusercontent.com/9997614/38518229-3ed15bf0-3bf1-11e8-871b-08fbf5196d5b.png)

**Comment by caom92** [comment]
@delcabo  La razón por la cual sólo aparece 1 zona para elegir es porque sólo tiene 1 usuario registrado.

![screenshot-2018-4-9 audit manager 1](https://user-images.githubusercontent.com/9997614/38518400-a059d1ea-3bf1-11e8-9c69-d9876e69edb9.png)

Esa caja de selección le listará todos los usuarios con rol de **Auditado** agrupados por zona, por lo que **no** listará aquellas zonas que no tengan usuarios registrados con ese rol. Por eso sólo le aparece a seleccionar la zona TST.

El sistema de Auditorías es un sistema aparte del sistema de bitćoras, pues habíamos acordado que estos dos sistemas no iban a estar integrados. Si estaba esperando ver listados los usuarios del sistema de bitácoras en esa pantalla, esto no va a suceder, sólo se van a listar los usuarios nuevos que usted registre en este sistema.

**Comment by caom92** [comment]
En cuanto al mensaje de error que aparece, ése problema ya lo arreglé, sin embargo descubrí otro error, pero me tomará un rato arreglarlo.
