### ISSUE TITLE
Eliminar SELECCION en pantalla de SUB-Modulos

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#28]
Quitar la opcion de selección de SUBMODULOS, es decir que cuando abra el modulo principal, salgan todas las preguntas de ese Modulo, , claro, separado por el titulo de submodulo que corresponda...

![image](https://user-images.githubusercontent.com/28766240/40018696-e2a7949c-5771-11e8-8aff-8272a7ce4fd1.png)

**Comment by caom92** [comment]
Ya quedó eliminado, ahora se despliegan todos los criterios de golpe. Los cambios se veerán aplicados en la próxima actualización
![lol](https://user-images.githubusercontent.com/9997614/40263917-b0176948-5ace-11e8-80ba-cefe6f469374.png)
