### ISSUE TITLE
Cambio de Letrero en auditoria FT...

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#49]
cambiar "CONFORMIDAD DEFINITIVA" a "A.C Aceptada?"

![image](https://user-images.githubusercontent.com/28766240/41941445-e017da38-7950-11e8-9eb1-dc5a63087448.png)

**Comment by caom92** [comment]
Ya quedó implementado

![screenshot-2018-6-27 audit manager 1](https://user-images.githubusercontent.com/9997614/41990046-2c69ac72-79f6-11e8-885d-4b266cf8c419.png)
