### ISSUE TITLE
Poner otra opcion en respuesta de Auditor en FT

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#50]
Adeherir N/A en opciones, pero que cuando se use, no afecte al score, simplemente es como una pregunta o registro NULA

![image](https://user-images.githubusercontent.com/28766240/41941607-5f0e5038-7951-11e8-8c36-a6c4f77c564a.png)

**Comment by caom92** [comment]
Me había dicho Juan Fidel que en lugar de recurrir a esta solución, se le ofreciera al Auditor, en la pantalla que le aparece al crear una nueva auditoría, una opción donde elija el **Plazo**, para remover aquellos criterios que no iban a ser necesarios de capturar para ésa auditoría (Ver #45 para más info.), pero ya luego me explicó Maricela que luego hay zonas donde algunos criterios no aplican y por eso desea que ésta opción esté disponible.

**Comment by caom92** [comment]
Estuve avanzando con esto, parece ser que la captura del Auditor y Auditado (1ra vez) ya quedó, falta revisar la generación de reportes

**Comment by delcabo** [comment]
excelente!!

**Comment by delcabo** [comment]
excelente!!

**Comment by caom92** [comment]
Creo que ya quedó. La opción le aparece al Auditor a la hora de capturar la auditoría. Cuando esta opción está marcada, el criterio no se cuenta en el puntaje del Auditado; por ejemplo, si hay 10 criterios, los cuales se calificaron de la sig. manera:

- 4 Sí fueron cumplidos
- 4 No fueron cumplidos y las A. C. no fueron aceptadas
- 2 fueron marcados como N/A

Entonces la calificación se evaluará en base a los 8 criterios que **no** fueron marcados como N/A; es decir, la calificación final del Auditado sería del 50% en este caso particular (4 criterios cumplidos dividido entre 8 criterios en total).

![screenshot-2018-6-29 audit manager](https://user-images.githubusercontent.com/9997614/42109222-c3b4eadc-7b91-11e8-9137-e20808f9c2c7.png)

Los criterios marcados como N/A aún se desplegarán en la pantalla de captura tanto para el Auditor como para el Auditado, cuando el botón azúl de **Ocultar Criterios** con el ícono del ojo esté **desactivado** (es decir, se está mostrando la lista completa de los criterios). Hay que recordar que el Auditor puede editar una auditoría en cualquiera de las etapas en que se encuentre, esto también aplica a los criterios marcados con N/A; si en algún punto así lo desea, el Auditor puede cambiar un criterio con N/A y asignarle una calificación válida o inválida de cumplimiento, así como también escribir comentarios y agregar archivos de evidencia; el Auditor no está restringido en éste aspecto. 

![screenshot-2018-6-29 audit manager 1](https://user-images.githubusercontent.com/9997614/42109500-b1a9a9f8-7b92-11e8-887c-3f6c8f08497e.png)

Sin embargo, en los reportes PDF, **no se imprimen** los criterios marcados con N/A. La idea es que los criterios con N/A, se despliegan en la pantalla de captura porque pueden ser editados mientras la auditoría se esté llevando a cabo, pero cuando se despliega el reporte, los criterios con N/A son omitidos porque técnicamente no aplican para ésta auditoría.

![na-test-report](https://user-images.githubusercontent.com/9997614/42109668-48f9426e-7b93-11e8-9b79-42622679cdb1.png)
_En esta imagen, nótese como el reporte comienza desde el criterio 1.1.2.a; esto es porque los criterios 1.1.1.a y 1.1.1.b fueron marcados como N/A y por lo tanto se omitieron en el reporte_

Mi sugerencia es que hagan un simulacro de auditoría y vean cómo el campo N/A afecta el cálculo del puntaje del Auditado y la impresión del reporte PDF y me digan si éste comportamiento es correcto y satisface sus necesidades o no.
