### ISSUE TITLE
Cuadro de texto y campo de link

### ISSUE THREAD

**Issue by delcabo** [caom92/audit-master#51]
Anexar a la audtoria general que el Auditor ponga, ajuste o borre lo de un cuadro general y un campo para poner link para fotos... 

![image](https://user-images.githubusercontent.com/28766240/42290764-36c1f64e-7f7c-11e8-8d4e-85b77f2f9edf.png)

**Comment by caom92** [comment]
Había olvidado agregar las notas en el reporte PDF. Si el campo de notas o el de enlace están vacíos, son omitidos del reporte, y en caso contrario se imprimen al inicio del reporte de criterios. 

![reporte](https://user-images.githubusercontent.com/9997614/42394948-cda890d2-8110-11e8-9567-c547303ba922.png)

**Comment by caom92** [comment]
Ya lo subí al servidor de Julio
